version: '3.4'

services:
    postgresql:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=htd-dev
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgresql-data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=0nhopass
        ports:
            - "5050:80"
        restart: always
        volumes:
            - pgadmin-data:/root/.pgadmin

volumes:
    postgresql-data:
    pgadmin-data:
    